<!doctype html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <div id="root"></div>
        <script src="bundle.js"></script>
        <script>
            setTimeout(
                () => {
                    console.log("After 1 second");
                    setTimeout(
                        ()  => {
                            console.log("After 2 seconds"),
                            setTimeout(
                                () => console.log("After 3 seconds"),
                                1000
                            );
                        },
                        1000
                     );
                },
                1000
            );
        </script>

        <script>
                const later = (delay) => new Promise((resolve) => setTimeout(resolve, delay));
                later(1000)
                .then(
                    () => {
                        console.log("After 1 second with promise");
                        return later(1000);
                    }) 
                .then(
                    () => {
                        console.log("After 2 second with promise");
                        return later(1000);
                    }) 
                .then(
                () => {
                    console.log("After 3 second with promise");
                    return later(1000);
                })
                .then(
                () => {
                    console.log("After 4 second with promise");
                }); 
        </script>

        <script>
            fetch("https://api.github.com/search/repositories?q=react")
            .then(response => response.json())
            .then(json => console.log(json))
            .catch(err => console.log("error fetching query"));
        </script>

        <script>
            Promise.resolve("This is a good value.")
            .then(message => message + "!")
            .then(betterMessage => Promise.reject("Intentionally failing"))
            .then(finalMessage => console.log(finalMessage))
            .catch(err => console.log(err));
        </script>
    </body>
</html>